[package]
name = "aoc2019-rust"
version = "0.1.0"
authors = ["Jeremy Kitchen <kitchen@kitchen.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day1"
path = "src/day1/day1.rs"
